GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiUmlmYWkiLCJlbWFpbCI6InJpZmFpQGdtYWlsLmNvbSIsImlhdCI6MTY4NTk2MjcxNX0.L7-V54EsKJzppSgThlfBBKYDYqrPFCtUymXM1MZVi-I
### register
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "fullname": "Ahmad",
    "username": "Rifai",
    "email": "aw@gmail.com",
    "password": "rahasia",
    "confirmPasssword": "rahasia"
}

### login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "rifai@gmail.com",
    "password": "rahasia"
}

### refresh token
GET http://localhost:3000/api/refresh_token

### logout
POST http://localhost:3000/api/logout

### get all stations
GET http://localhost:3000/api/stations

### create stations
POST http://localhost:3000/api/stations
Content-Type: application/json

{
    "name": "Station Cikampek 2",
    "city": "Cikampek 2",
    "address": "Jalan Pahlawan nomer 5 2",
    "latitude": 0,
    "longitude": 0
}

### get station by id
GET http://localhost:3000/api/stations/2


### delete station by id
DELETE http://localhost:3000/api/stations/3